opacity-rule = [
  "95:class_g = 'Rofi'",
  "95:class_g = 'Alacritty'"
];

shadow-exclude = [
  "name = 'i3 frames'",
  "class_g = 'i3-frame'"
];

blur = [
  "method = 'gaussian'",
  "size = 30",
  "deviation = 10.0"
];

blur-background = true
blur-background-frame = true
